# Generated by Django 4.0 on 2022-02-25 02:24
from django.contrib.auth.hashers import make_password
from django.db import migrations
from pkg_resources import AvailableDistributions
#from django.utils import timezone
from datetime import datetime, timezone
#import pytz

#from jobs.models import Owner, Job, Customer, Worker, AvailableTimes, JobType
def populate_db(apps, schema_editor):
    # Owner = apps.get_model('jobs', 'Owner')
    # Job = apps.get_model('jobs', 'Job')
    # Customer = apps.get_model('jobs', 'Customer')
    # Worker = apps.get_model('jobs', 'Worker')
    # AvailableTimes = apps.get_model('jobs', 'AvailableTimes')
    # JobType = apps.get_model('jobs', 'JobType')

    # # Create 3 Job types: Mowing, Blowing, Raking
    
    # jobTypeMowing = JobType(jobType="Lawn Mowing")
    # jobTypeMowing.save()
    # jobTypeBlowing = JobType(jobType="Snow Blowing")
    # jobTypeBlowing.save()
    # jobTypeRaking = JobType(jobType="Leaf Raking")
    # jobTypeRaking.save()

    # # Create 2 customers
    # customerGerald = Customer(
    #         password="gerald", email="gerald@whoami.com", 
    #         username="geraldunkown",   first_name="Gerald", 
    #         last_name="NoLastName", balance=1337,
    #         zipCode=84321, accountType='C', phoneNumber="621-555-4516", 
    #         defaultAddress="123 Wizard Way", averageRating=5, numberOfRatings=3
    #     )
    # customerGerald.password=make_password("gerald")
    # customerGerald.save()

    # customerDean = Customer(
    #         password="mary2005", email="deanw@hotmail.com", 
    #         username="impala67",   first_name="Dean", 
    #         last_name="Winchester", balance=1500.0,
    #         zipCode=66952, accountType='C', phoneNumber="785-555-0128", 
    #         defaultAddress="1967 Winchester Avenue", averageRating=4.5, numberOfRatings=576
    #     )
    # customerDean.password= make_password("mary2005")
    # customerDean.save()

    # # Create 2 workers
    # workerBilly = Worker(
    #         password="billyjoel", email="billy@joel.com",
    #         username="billyjoel",   first_name="Billy", 
    #         last_name="Joel", balance=1337.0,
    #         zipCode=84341, accountType='W', maximumTravelDistance=25
    #     )

    # workerBilly.password = make_password("billyjoel")

    # workerBilly.save()
    # workerBilly.jobTypes.add(jobTypeMowing, jobTypeBlowing)

    # workerSam = Worker(
    #         password="sammy_boy1967", email="samw@hotmail.com", 
    #         username="sammyw",   first_name="Sam", 
    #         last_name="Winchester", balance=1983.0,
    #         zipCode=66952, accountType='W', maximumTravelDistance=300
    #     )
    # workerSam.password=make_password("sammy_boy1967")
    # workerSam.save()
    # workerSam.jobTypes.add(jobTypeMowing, jobTypeBlowing, jobTypeRaking)

    # #Create 3 jobs, link to customers and jobtypes

    # jobMowing = Job(
    #     price=57.0, address="4589 S 4875 N Paris, Idaho", zipCode=83261, 
    #     time=datetime(2022, 5, 1, 12, 59, 28, 0, timezone.utc), recurring=True,
    #     rating=False, completionTime=90.0, status='P', customer_id=customerGerald.id,
    #     jobType_id=jobTypeMowing.id
    # )
    # jobMowing.save()

    # jobRaking = Job(
    #     price=800.0, address="7459 Gold St.", zipCode=84321, 
    #     time=datetime(2022, 5, 16, 18, 00, 00, 0, timezone.utc), recurring=False,
    #     rating=False, completionTime=20.0, status='P', customer_id=customerGerald.id,
    #     jobType_id=jobTypeRaking.id
    # )
    # jobRaking.save()

    # jobBlowing = Job(
    #     price=1337.0, address="That creepy house down the way", zipCode=70118, 
    #     time=datetime(2022, 5, 26, 16, 30, 21, 0, timezone.utc), recurring=True,
    #     rating=True, completionTime=-5.5, status='P', customer_id=customerDean.id,
    #     jobType_id=jobTypeBlowing.id
    # )
    # jobBlowing.save()

    # # Create an owner

    # owner = Owner(
    #     password="owner", username="owner", email="owner@boss.com", first_name="Awesome", 
    #     last_name="Owner", balance=0, zipCode=11111, accountType='O'
    # )
    # owner.save()
    pass




class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db)
    ]
