# Generated by Django 3.2.8 on 2022-03-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_populate'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='refunddescription',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('D', 'Due'), ('I', 'Disputed'), ('F', 'Finished')], default='P', max_length=1),
        ),
    ]
