# Generated by Django 3.2.8 on 2022-03-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20220318_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='completionTime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='rating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='refunddescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
