# Generated by Django 4.0 on 2022-03-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20220318_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabletimes',
            name='fromTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availabletimes',
            name='toTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Active'), ('D', 'Due'), ('I', 'Disputed'), ('F', 'Finished'), ('R', 'Reviewed')], default='P', max_length=1),
        ),
    ]
